## 00. Pytorch Fundamentals

In [2]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cpu


In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


## Introduction to tensors

### Creating tensors

In [ ]:
#Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
# Get tensor back as Python int
scalar.item()

7

In [ ]:
# Vector
vector= torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
#TENSOR
TENSOR=torch.tensor([[[1,2,3],
                [3,6,9],
                [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [ ]:
TENSOR[0][1]

tensor([3, 6, 9])

### Random Tensors

Why random tensors?
Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`



In [ ]:
#Creating a random tensor of size (3,4)
random_tensor = torch.rand(3,4) #torch.rand(size(3,4)) can be used either way
random_tensor

tensor([[0.8292, 0.7149, 0.4973, 0.4525],
        [0.5002, 0.9371, 0.7061, 0.8656],
        [0.3567, 0.1874, 0.0597, 0.2259]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_tensor.shape

torch.Size([3, 4])

In [ ]:
#Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224)) # color channels(R,G,B),height,weight
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and Ones



In [ ]:
#Creating a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#Creating a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [ ]:
one_to_ten= torch.arange(start=1,end=11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [ ]:
#FLoat 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, # e.g. float_32
                               device=None, # e.g. cuda
                               requires_grad=False) # tracking for gradients
float_32_tensor,float_32_tensor.dtype

(tensor([3., 6., 9.]), torch.float32)

In [ ]:
float_16_tensor= float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

### Tensor attributes

In [ ]:
#Creating renmod tensors
some_tensor= torch.rand(3,4)
some_tensor

tensor([[0.7761, 0.4382, 0.6926, 0.8572],
        [0.5304, 0.8926, 0.1445, 0.1105],
        [0.8515, 0.3689, 0.3099, 0.8734]])

In [ ]:
#Attributes -> .size #Functions -> .size()
some_tensor.shape,some_tensor.size

(torch.Size([3, 4]), <function Tensor.size>)

In [ ]:
some_tensor.size()

torch.Size([3, 4])

In [ ]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on:{some_tensor.device}")

tensor([[0.7761, 0.4382, 0.6926, 0.8572],
        [0.5304, 0.8926, 0.1445, 0.1105],
        [0.8515, 0.3689, 0.3099, 0.8734]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on:cpu


### Manipulating tensors

* Addition
* Subtraction
* Multiplication(element wise)
* Division
* Matrix multiplication



In [3]:
tensor = torch.tensor([3,4,5])
tensor

tensor([3, 4, 5])

In [ ]:
tensor*10

tensor([30, 40, 50])

In [ ]:
#other way
mul_tensor = torch.mul(tensor,10)
mul_tensor

tensor([3000, 4000, 5000])

### Matrix multiplication

> There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
    * `(3,2) @ (3,2)` -> won't work
    * `(3,4) @ (4,3)` -> will work
    * `(4,3) @ (3,4)` -> will work
2. The resulting matrix has the shape of **outer dimensions**:
    * `(2,3) @ (3,2)` -> `(2,2)`
    * `(3,2) @ (2,2)` -> `(3,3)`



In [7]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[1.3881, 1.2819, 0.6917],
        [0.7343, 0.7161, 0.2687],
        [0.6957, 0.5865, 0.4895]])

In [4]:
#Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor*tensor}")

tensor([3, 4, 5]) * tensor([3, 4, 5])
Equals: tensor([ 9, 16, 25])


In [5]:
#Matrix multiplication
%%time
torch.matmul(tensor,tensor)

CPU times: user 947 µs, sys: 993 µs, total: 1.94 ms
Wall time: 24.9 ms


tensor(50)

In [6]:
tensor @ tensor #same as matmul/matrix multiplication

tensor(50)

In [ ]:
### One of the most